openapi: 3.0.0
info:
  title: Agora Webhooks
  description: |
    Spec for webhooks called by the Agora services. The paths are examples only - each
    app can configure their own.
  version: 1.0.0

paths:
  /sign_transaction:
    post:
      summary: |
        A webhook for Agora services to submit transactions for signing. Each app is responsible for validating the
        transaction contents prior to signing and returning the transaction. Developers should expect that any
        transaction envelope payload returned in a 200 response will be submitted to Horizon.
      parameters:
        - in: header
          name: X-App-User-ID
          schema:
            type: string
        - in: header
          name: X-App-User-Token
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignTransactionRequestBody"
      responses:
        '200':
          description: "Must contain the transaction payload, signed by the service."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignTransactionSuccessResponse"
        '400':
          description: "Indicates that the request was malformed or contained invalid arguments."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignTransactionBadRequestResponse"
        '403':
          description: "Indicates that the service refused to sign the transaction."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignTransactionForbiddenResponse"
        '404':
          description: "Indicates that one or more resources referenced in the request could not be found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignTransactionNotFoundResponse"

components:
  schemas:
    # Shared schemas
    TransactionEnvelopeXDR:
      description: "A base64-encoded transaction envelope XDR."
      type: string
      format: byte
    InvoiceList:
      description: |
        A base64-encoded protobuf InvoiceList related to a transaction. Each invoice corresponds to an operation in the transaction.
      type: string
      format: byte

    # Sign Transaction Webhook schemas
    SignTransactionRequestBody:
      description: |
        The body of a a sign transaction request. Contains a transaction payload that should be verified prior to
        signing. If an invoice list is present, it contains data regarding what the transaction is for.
      type: object
      required:
        - envelope_xdr
      properties:
        envelope_xdr:
          $ref: "#/components/schemas/TransactionEnvelopeXDR"
        invoice_list:
          $ref: "#/components/schemas/InvoiceList"

    SignTransactionSuccessResponse:
      description: |
        The expected response for a successful sign transaction request. Contains the signed transaction envelope, which
        will be submitted by the requesting Agora service.
      type: object
      required:
        - envelope_xdr
      properties:
        envelope_xdr:
          $ref: "#/components/schemas/TransactionEnvelopeXDR"
    SignTransactionBadRequestResponse:
      type: object
      properties:
        message:
          type: string
          example: "'envelope_xdr' was invalid"
    SignTransactionForbiddenResponse:
      type: object
      properties:
        message:
          type: string
          example: "the operation at index 0 has the wrong source account"
        errors:
          type: array
          items:
            type: object
            properties:
              operation_index:
                description: "the index of the operation the error pertains to"
                type: integer
              reason:
                type: string
                enum:
                  - wrong_destination
                  - already_paid
                description: |
                  * `wrong_destination`: the destination account was incorrect
                  * `already_paid`: the user has already paid for the submitted invoice
    SignTransactionNotFoundResponse:
      type: object
      properties:
        message:
          type: string
          example: "SKU 'SKU#1' could not be found"
